version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  node:
    build: .
    container_name: shark-node
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  mongo-data:
